# Generated by Django 3.2.9 on 2021-11-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_no', models.IntegerField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('student_DOB', models.DateField()),
                ('student_GPA', models.FloatField()),
                ('student_address', models.TextField(null=True)),
                ('student_phone_no', models.IntegerField(max_length=12)),
                ('student_section', models.CharField(choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C')], max_length=10)),
            ],
        ),
    ]
